name: Build Mac VST3 + AU

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install CMake + Ninja
        run: brew install cmake ninja

      - name: Configure CMake
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13

      - name: Build Plugin
        run: cmake --build build --config Release --parallel

      - name: Upload Mac Builds
        uses: actions/upload-artifact@v4
        with:
          name: LusionSmartReverb-Mac
          path: |
            build/**/*.vst3
            build/**/*.component
          if-no-files-found: warn
